export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  description: string
  longDescription?: string
  image: string
  category: string
  rating: number
  reviews: number
  stock: number
  specs?: Record<string, string>
}

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Fones de Ouvido Premium Sem Fio",
    price: 199.99,
    originalPrice: 249.99,
    description: "Cancelamento de ruído com bateria de 30 horas",
    longDescription:
      "Experimente áudio pristino com tecnologia de cancelamento de ruído ativo e drivers premium de 40mm. Perfeito para viagens, trabalho e entretenimento com uma incrível bateria de 30 horas.",
    image: "/premium-wireless-headphones-black.jpg",
    category: "Áudio",
    rating: 4.8,
    reviews: 324,
    stock: 15,
    specs: {
      "Tamanho do Driver": "40mm",
      "Duração da Bateria": "30 horas",
      ANC: "Sim",
      Peso: "250g",
    },
  },
  {
    id: "2",
    name: "Relógio Inteligente Pro",
    price: 349.99,
    originalPrice: 399.99,
    description: "Rastreamento de fitness com bateria de 7 dias",
    longDescription:
      "Rastreamento de fitness avançado com monitor de frequência cardíaca, GPS e rastreamento de sono. Apresenta display AMOLED sempre ligado e até 7 dias de vida útil da bateria.",
    image: "/smart-watch-pro-sport.jpg",
    category: "Wearables",
    rating: 4.6,
    reviews: 218,
    stock: 22,
    specs: {
      Display: "AMOLED 1.3in",
      Bateria: "7 dias",
      "À Prova de Água": "5ATM",
      Sensores: "6-axis",
    },
  },
  {
    id: "3",
    name: "Webcam Pro 4K",
    price: 129.99,
    originalPrice: 159.99,
    description: "Câmera de streaming profissional 4K",
    longDescription:
      "Capture vídeo em 4K a 60fps com foco automático avançado e correção de luz baixa. Microfone embutido com supressão de ruído.",
    image: "/4k-webcam-professional.jpg",
    category: "Câmeras",
    rating: 4.7,
    reviews: 156,
    stock: 31,
    specs: {
      Resolução: "4K@60fps",
      Lente: "120° FOV",
      Áudio: "Microfone estéreo",
      Conexão: "USB-C",
    },
  },
  {
    id: "4",
    name: "Teclado Mecânico para Jogos RGB",
    price: 159.99,
    originalPrice: 199.99,
    description: "Mecânico com switches personalizáveis",
    longDescription:
      "Teclado mecânico premium com switches intercambiáveis, teclas programáveis e iluminação RGB personalizável. Projetado para gamers e digitadores.",
    image: "/mechanical-keyboard-rgb-gaming.jpg",
    category: "Periféricos",
    rating: 4.9,
    reviews: 427,
    stock: 18,
    specs: {
      Switch: "Intercambiável",
      Backlight: "RGB",
      Layout: "TKL",
      Material: "Alumínio",
    },
  },
  {
    id: "5",
    name: "Mouse Sem Fio Ergonômico",
    price: 59.99,
    originalPrice: 79.99,
    description: "Rastreamento preciso com bateria de 12 meses",
    longDescription:
      "Design ergonômico reduz tensão no pulso com rastreamento preciso e configurações de DPI personalizáveis. Vida útil excepcional de bateria de 12 meses.",
    image: "/wireless-mouse-ergonomic.jpg",
    category: "Periféricos",
    rating: 4.5,
    reviews: 289,
    stock: 45,
    specs: {
      DPI: "16000",
      Bateria: "12 meses",
      Botões: "6",
      Peso: "95g",
    },
  },
  {
    id: "6",
    name: "Hub USB-C 7 em 1",
    price: 79.99,
    originalPrice: 99.99,
    description: "Hub multi-porta com HDMI e leitor de cartão",
    longDescription:
      "Expanda a conectividade com saída HDMI 4K, portas USB 3.0, leitor de cartão SD e power delivery. Design de alumínio compacto.",
    image: "/usb-c-hub-multiport.jpg",
    category: "Acessórios",
    rating: 4.4,
    reviews: 134,
    stock: 28,
    specs: {
      Portas: "7",
      HDMI: "4K@30Hz",
      Power: "100W PD",
      Material: "Alumínio",
    },
  },
  {
    id: "7",
    name: "SSD Portátil 1TB",
    price: 139.99,
    originalPrice: 179.99,
    description: "Armazenamento externo rápido com design resistente",
    longDescription:
      "SSD portátil de alta velocidade com velocidades de leitura de até 1050MB/s. Construção de alumínio resistente. Perfeito para criadores e profissionais.",
    image: "/portable-ssd-external-storage.jpg",
    category: "Armazenamento",
    rating: 4.7,
    reviews: 201,
    stock: 12,
    specs: {
      Capacidade: "1TB",
      Velocidade: "1050MB/s",
      Interface: "USB 3.2",
      Tamanho: "Bolso",
    },
  },
  {
    id: "8",
    name: "Luminária de Mesa LED Inteligente",
    price: 49.99,
    originalPrice: 69.99,
    description: "Atenuável com temperatura de cor ajustável",
    longDescription:
      "Luminária LED eficiente em energia com controle por toque, brilho ajustável e temperatura de cor de 3000K a 6500K. Porta de carregamento USB incluída.",
    image: "/led-desk-lamp-modern.jpg",
    category: "Iluminação",
    rating: 4.3,
    reviews: 178,
    stock: 35,
    specs: {
      Potência: "8W LED",
      Temperatura: "3000-6500K",
      Controle: "Toque",
      "Porta USB": "Sim",
    },
  },
  {
    id: "9",
    name: "Fones de Ouvido com Cancelamento de Ruído",
    price: 129.99,
    originalPrice: 159.99,
    description: "TWS compacto com ANC e bateria de 8 horas",
    longDescription:
      "Fones de ouvido true wireless com cancelamento de ruído ativo, modo transparência e 8 horas de bateria por carga. Resistente à água IPX4.",
    image: "/wireless-earbuds.png",
    category: "Áudio",
    rating: 4.7,
    reviews: 312,
    stock: 42,
    specs: {
      ANC: "Sim",
      Bateria: "8 horas",
      Drivers: "8mm",
      "Resistência à Água": "IPX4",
    },
  },
  {
    id: "10",
    name: "Projetor Portátil 4K",
    price: 599.99,
    originalPrice: 799.99,
    description: "4K nativo com 500 lumens de brilho",
    longDescription:
      "Projetor portátil compacto com resolução 4K nativa, keystone automático e brilho impressionante de 500 lumens. Alto-falante integrado com bateria de 10000mAh.",
    image: "/portable-projector-4k.jpg",
    category: "Projetores",
    rating: 4.8,
    reviews: 89,
    stock: 8,
    specs: {
      Resolução: "4K",
      Lumens: "500",
      Bateria: "10000mAh",
      Tamanho: "Compacto",
    },
  },
  {
    id: "11",
    name: "Estação de Carregamento Sem Fio",
    price: 39.99,
    originalPrice: 49.99,
    description: "Carregador multi-dispositivo com 5 bobinas",
    longDescription:
      "Carregue até 3 dispositivos simultaneamente com dissipação de calor avançada. Funciona com todos os smartphones e acessórios habilitados para Qi.",
    image: "/wireless-charging-pad-multi-device.jpg",
    category: "Acessórios",
    rating: 4.6,
    reviews: 245,
    stock: 58,
    specs: {
      Saída: "15W",
      Dispositivos: "3",
      Bobinas: "5",
      Indicador: "LED",
    },
  },
  {
    id: "12",
    name: "Monitor para Jogos Vertical 27 polegadas",
    price: 349.99,
    originalPrice: 449.99,
    description: "1440p 144Hz com suporte HDR",
    longDescription:
      "Monitor profissional para jogos com resolução 2560x1440, taxa de atualização de 144Hz e suporte HDR10. Perfeito para jogos competitivos e criação de conteúdo.",
    image: "/gaming-monitor-27-inch-144hz.jpg",
    category: "Monitores",
    rating: 4.9,
    reviews: 203,
    stock: 11,
    specs: {
      Resolução: "1440p",
      TaxaDeAtualização: "144Hz",
      Resposta: "1ms",
      HDR: "Sim",
    },
  },
  {
    id: "13",
    name: "Mousepad para Jogos RGB XL",
    price: 29.99,
    originalPrice: 39.99,
    description: "Grande superfície para jogos com RGB",
    longDescription:
      "Mousepad para jogos extra grande com superfície de pano macio e iluminação RGB. Bordas costuradas para durabilidade e rastreamento preciso.",
    image: "/gaming-mousepad-rgb-xl.jpg",
    category: "Periféricos",
    rating: 4.5,
    reviews: 167,
    stock: 72,
    specs: {
      Tamanho: "90x40cm",
      RGB: "Sim",
      Superfície: "Pano",
      Espessura: "3mm",
    },
  },
  {
    id: "14",
    name: "Carregador Multi USB-C",
    price: 44.99,
    originalPrice: 59.99,
    description: "65W dual USB-C com estojo de viagem",
    longDescription:
      "Carregador compacto dual USB-C com potência combinada de 65W. Inclui estojo de viagem e suporte para power delivery para laptops e telefones.",
    image: "/usb-c-charger-65w-dual.jpg",
    category: "Acessórios",
    rating: 4.7,
    reviews: 198,
    stock: 33,
    specs: {
      Potência: "65W",
      Portas: "2x USB-C",
      Estojo: "Incluído",
      Viagem: "Compacto",
    },
  },
  {
    id: "15",
    name: "Organizador de Cabos Premium",
    price: 24.99,
    originalPrice: 34.99,
    description: "Gerenciador de cabos em silicone com 5 slots",
    longDescription:
      "Organizador de cabos em silicone premium com 5 slots para manter sua mesa organizada. Com suporte adesivo 3M e design magnético.",
    image: "/cable-organizer-desk.jpg",
    category: "Acessórios",
    rating: 4.4,
    reviews: 214,
    stock: 89,
    specs: {
      Slots: "5",
      Material: "Silicone",
      Adesivo: "3M",
      Magnético: "Sim",
    },
  },
  {
    id: "16",
    name: "Caixa de Som Portátil Pro",
    price: 89.99,
    originalPrice: 119.99,
    description: "Som 360° com bateria de 20 horas",
    longDescription:
      "Caixa de som portátil à prova d'água com som surround 360°, bateria de 20 horas e design resistente. Perfeito para aventuras ao ar livre.",
    image: "/portable-speaker-waterproof.jpg",
    category: "Áudio",
    rating: 4.6,
    reviews: 276,
    stock: 25,
    specs: {
      Potência: "20W",
      Bateria: "20h",
      AProvaDeAgua: "IPX7",
      Alcance: "30m",
    },
  },
  {
    id: "17",
    name: "Ring Light Studio",
    price: 69.99,
    originalPrice: 89.99,
    description: "10 polegadas LED com suporte para telefone",
    longDescription:
      "Ring light LED profissional de 10 polegadas com brilho ajustável e temperatura de cor. Inclui suporte resistente para telefone e tripé.",
    image: "/ring-light-led-10-inch.jpg",
    category: "Iluminação",
    rating: 4.8,
    reviews: 312,
    stock: 19,
    specs: {
      Tamanho: "10 polegadas",
      LED: "SMD",
      Temperatura: "3200-5600K",
      Suporte: "Incluído",
    },
  },
  {
    id: "18",
    name: "Cabo HDMI 2.1",
    price: 14.99,
    originalPrice: 19.99,
    description: "Certificado ultra-rápido 8K@60Hz",
    longDescription:
      "Cabo HDMI 2.1 de alta qualidade com suporte a resolução 8K a 60Hz. Perfeito para consoles de jogos e monitores premium.",
    image: "/hdmi-cable-2-1.jpg",
    category: "Cabos",
    rating: 4.7,
    reviews: 134,
    stock: 156,
    specs: {
      Versao: "2.1",
      Resolucao: "8K@60Hz",
      Comprimento: "2m",
      Certificacao: "Oficial",
    },
  },
  {
    id: "19",
    name: "Suporte de Laptop em Alumínio",
    price: 34.99,
    originalPrice: 49.99,
    description: "Ângulo ajustável com dissipação de calor",
    longDescription:
      "Suporte premium de alumínio para laptop com altura e ângulo ajustáveis. Melhora a postura e oferece excelente dissipação de calor para seu dispositivo.",
    image: "/laptop-stand-aluminum-adjustable.jpg",
    category: "Acessórios",
    rating: 4.6,
    reviews: 267,
    stock: 47,
    specs: {
      Material: "Alumínio",
      CargaMaxima: "15kg",
      Ajustavel: "Sim",
      Portatil: "Dobravel",
    },
  },
  {
    id: "20",
    name: "Headset para Jogos Elite",
    price: 149.99,
    originalPrice: 199.99,
    description: "Surround 7.1 com microfone com cancelamento de ruído",
    longDescription:
      "Headset profissional para jogos com som surround virtual 7.1, microfone com cancelamento de ruído e almofadinhas ultra confortáveis.",
    image: "/gaming-headset-professional.jpg",
    category: "Áudio",
    rating: 4.8,
    reviews: 298,
    stock: 21,
    specs: {
      Som: "7.1 Surround",
      Microfone: "Cancelamento de Ruído",
      Drivers: "50mm",
      Impedancia: "32 Ohm",
    },
  },
  {
    id: "21",
    name: "Disco Rígido Externo 2TB",
    price: 69.99,
    originalPrice: 89.99,
    description: "Armazenamento de backup rápido USB 3.0",
    longDescription:
      "Disco rígido externo confiável de 2TB com conectividade USB 3.0. Perfeito para backup e transferência de arquivos com operação plug-and-play.",
    image: "/placeholder.svg?height=300&width=300",
    category: "Armazenamento",
    rating: 4.5,
    reviews: 189,
    stock: 34,
    specs: {
      Capacidade: "2TB",
      Velocidade: "USB 3.0",
      RPM: "5400",
      Cache: "64MB",
    },
  },
  {
    id: "22",
    name: "Câmera de Ação 4K",
    price: 199.99,
    originalPrice: 279.99,
    description: "À prova d'água com estabilização de imagem",
    longDescription:
      "Câmera de ação profissional 4K com design à prova d'água, estabilização de imagem avançada e lente grande angular. Perfeita para esportes e aventura.",
    image: "/placeholder.svg?height=300&width=300",
    category: "Câmeras",
    rating: 4.7,
    reviews: 145,
    stock: 16,
    specs: {
      Resolucao: "4K@60fps",
      AProvaDeAgua: "30m",
      Estabilizacao: "Sim",
      Lente: "170 graus",
    },
  },
  {
    id: "23",
    name: "Pacote de Switches Mecânicos",
    price: 44.99,
    originalPrice: 59.99,
    description: "110 peças de switches mecânicos premium",
    longDescription:
      "Switches de teclado mecânico premium com atuação suave e construção durável. Inclui 110 switches para personalização completa do teclado.",
    image: "/placeholder.svg?height=300&width=300",
    category: "Periféricos",
    rating: 4.9,
    reviews: 156,
    stock: 58,
    specs: {
      Quantidade: "110",
      Tipo: "Linear",
      Atuacao: "45g",
      VidaUtil: "80M cliques",
    },
  },
  {
    id: "24",
    name: "Hub USB 3.0 Alimentado",
    price: 32.99,
    originalPrice: 44.99,
    description: "4 portas com adaptador de energia separado",
    longDescription:
      "Hub USB 3.0 alimentado com 4 portas e interruptores individuais. Vem com adaptador de energia para desempenho confiável com dispositivos de alta potência.",
    image: "/placeholder.svg?height=300&width=300",
    category: "Acessórios",
    rating: 4.6,
    reviews: 122,
    stock: 41,
    specs: {
      Portas: "4",
      USB: "3.0",
      Potencia: "5A",
      VelocidadeDados: "5Gbps",
    },
  },
]
